config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  resources :posts do
    resources :likes
    resources :comments do 
      resources :likes
    end
  end
  devise_for :users, controllers: { sessions: 'sessions',registrations: 'registrations',:omniauth_callbacks => 'users/omniauth_callbacks' }
  get 'welcome/index'
  root 'welcome#index'
  
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
       devise_scope :user do
         post 'signup' => 'registrations#create'
         post 'signin' => 'sessions#create'
       end
    end
 end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
#

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :post
	has_many :likes, as: :likeable,dependent: :destroy
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def new
		
		@post = Post.find(params[:post_id])
		@comment = Comment.new
	end
	def create
		
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(user_id: current_user.id, post_id: @post.id, comment: params[:comment][:comment])
		

		# if @comment.save		
		# redirect_to post_path(@post)
	end

	def show
		@post = Post.find(params[:post_id])
		@comment = @post.comments
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<% post = Post.find_by(id:post)%>
<% post.comments.each do |comment|%>
    
	<p><%= comment.comment %>
	   <%#= comment.likes.count%><br>

	   <%# pre_like = comment.likes.find { |like| like.user_id == current_user.id} %>
	  <%# if pre_like %>
		<%#= link_to "LikeComment", post_comment_likes_path(@post,comment_id: comment.id), method: :post ,remote:true %>
	   <%#end%>
	</p>

<% end %>

app/views/comments/_form.html.erb
<%= form_for [@post, @post.comments.build],remote:true,html: {id: "commentForm"}  do |f| %>
  <div class="row">
    
      <%= f.label 'New comments' %>
  
      <%= f.text_area :comment,id: 'input',class:"textfield" %>
   
    
  </div>
    
  <%= f.submit 'Submit',class:"button btn btn-success",id:"formButton"%>
<% end %>

app/views/comments/create.js.erb
$("#comment_<%= @post.id %>").html("<%= escape_javascript(render partial: 'comments/comment',locals: { post: @comment.post_id} ) %>"); 
$('#input').val('');

app/views/comments/new.js.erb
<%# debugger %>
$("#<%= @post.id %>").html("<%= escape_javascript(render partial: 'comments/form',locals: { post: @comment.post_id} ) %>"); 