config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  resources :posts do
    resources :likes
    resources :comments do 
      resources :likes
    end
  end
  devise_for :users, controllers: { sessions: 'sessions',registrations: 'registrations',:omniauth_callbacks => 'users/omniauth_callbacks' }
  get 'welcome/index'
  root 'welcome#index'
  
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
       devise_scope :user do
         post 'signup' => 'registrations#create'
         post 'signin' => 'sessions#create'
       end
    end
 end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
#

app/models/like.rb
class Like < ApplicationRecord
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :find_post
	before_action :find_like, only: [:destroy]

	def create
		#debugger
		if @comment.present? 
			if already_liked?
				flash[:notice] = "You can't like more than once"
			else
				@comment.likes.create(user_id: current_user.id)
			end
		else
			if already_liked?
				flash[:notice] = "You can't like more than once"
			else
				@like = @post.likes.create(user_id: current_user.id)
				@post = Post.find(params[:post_id])
			end
			#redirect_to post_path(@post)
		end
	end

	def destroy

		if !(already_liked?)
			flash[:notice] = "Cannot unlike"
		else
			@like.destroy
			@post = Post.find(params[:post_id])
		end
		# redirect_to post_path(@post)
	end

	private
	def find_post
		# debugger
		if params[:comment_id]
			@comment = Comment.find(params[:comment_id])
		else	
			@post = Post.find(params[:post_id])
		end
	end


	def already_liked?
		if params[:comment_id]
			Like.where(user_id: current_user.id, likeable_id:
				params[:comment_id]).exists?
		else
			Like.where(user_id: current_user.id, likeable_id:
				params[:post_id]).exists?
		end
	end

	def find_like
		@like = @post.likes.find(params[:id])
	end

end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like_post.html.erb
<%if current_user.present?%>
<% post = Post.find_by(id:post)%>
<% pre_like = post.likes.find { |like| like.user_id == current_user.id} %>
<% if pre_like %>
<span id="likkke_<%=post.id%>"><%= post.likes.count %></span>
<span id= "like_btn"><%= link_to 'Unlike',post_like_path(post, pre_like), method: :delete, remote: true, id: "unlike_post_#{post.id}" %></span>
<% else %>
<span id="likkke_<%=post.id%>"><%= post.likes.count %></span>
<span id= "like_btn"><%= link_to 'Like',post_likes_path(post), method: :post, remote:true, id: "like_post_#{post.id}" %>
<% end %></span>
<%end%>

app/views/likes/create.js.erb
$("#likkke_<%= @post.id %>").html("<%= escape_javascript(render partial: 'likes/like_post',locals: { post: @post} ) %>"); 




 

app/views/likes/destroy.js.erb
$("#likkke_<%= @post.id %>").html("<%= escape_javascript(render partial: 'likes/like_post',locals: { post: @post} ) %>"); 


 