config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  resources :posts do
    resources :likes
    resources :comments do 
      resources :likes
    end
  end
  devise_for :users, controllers: { sessions: 'sessions',registrations: 'registrations',:omniauth_callbacks => 'users/omniauth_callbacks' }
  get 'welcome/index'
  root 'welcome#index'
  
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
       devise_scope :user do
         post 'signup' => 'registrations#create'
         post 'signin' => 'sessions#create'
       end
    end
 end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
#

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @posts = Post.paginate(page: params[:page], per_page: 9)
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div class="row">
  <% @posts.each do |post| %>
 <div class="col-sm-4">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title"><%=post.title%></h5>
      <%=image_tag(post.image.url , width:150)%>
      <p class="card-text"><%=post.description%></p>

      <div id = "likkke_<%= post.id%>">
        <strong>Likes</strong>
        <%= render 'likes/like_post',post:post %>
      </div>

      <div class= "row">
        <div class="col-sm-3">
          <%=link_to'AddComment',new_post_comment_path(post.id),remote:true,class:"btn btn-primary"%>
         <div id= "<%= post.id %>"></div>
        </div>
        <div class="col-sm-3">
          <%=link_to'ShowComment',post_path(post.id),remote:true,class:"btn btn-primary",id:"show_com_#{post.id}" %>
          <div id= "<%= post.id %>"></div>
          <button class="btn btn-primary" id= "rvm_com_<%= post.id %>" style="display :none; margin-top: inherit; margin-left: inherit;"  onclick= "hideComments()" >show_comment</button>
        </div>   
      </div>

      
<script type="text/javascript">

  $("#new_comment").submit(function(event) {
    event. preventDefault();
  // var post_id = "<%#= @post.id %>"
  var data = $("#new_comment").serialize();
    $.ajax({
      url: "/posts/"+<%= post.id %>+"/comments",
      type: 'POST', 
      data: data
    });
  });
</script>

<script>

    // $("rvm_com_<%= post.id %>").click(function(){
    //   // $("post_comment").toggle();
    //   $("#<%= post.id %>").css("display", "none");
    // });

    function hideComments(){
      
     $("#post_comment").css("display", "none");

   }

 </script>
 <%=link_to 'ViewPost',post_path(post.id),class:"btn btn-dark"%>


</div>
</div>
</div>

<%end%>
</div>
 <%=link_to 'NewPost',new_post_path,class:"btn btn-success"%>