config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  resources :posts do
    resources :likes
    resources :comments do 
      resources :likes
    end
  end
  devise_for :users, controllers: { sessions: 'sessions',registrations: 'registrations',:omniauth_callbacks => 'users/omniauth_callbacks' }
  get 'welcome/index'
  root 'welcome#index'
  
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
       devise_scope :user do
         post 'signup' => 'registrations#create'
         post 'signin' => 'sessions#create'
       end
    end
 end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
#

app/models/post.rb
class Post < ApplicationRecord

    has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" },default_url: ':style/default.png'
    validates_attachment :image,
    content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
    belongs_to :user
    has_many :comments
    has_many :likes, as: :likeable,dependent: :destroy
     validates :title, presence: true

      # validates_uniqueness_of :title, scope: :user_id

      validates :title, presence: true, uniqueness: { scope: :user_id }

    # validates :title,
    # uniqueness: {
    #   # object = person object being validated
    #   # data = { model: "Person", attribute: "Username", value: <username> }
    #   message: ->(object, data) do
    #     "Hey #{object.title}, #{data[:value]} is already taken."
    # end
# }

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  #before_action :authenticate_user! , only: [:create]
  before_action :authenticate_user!, except: [:new, :create,:show]
  respond_to :json

   #before_action :process_token
  # before_action :user_admin

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    
    #@user = User.find(params[:id])
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    # @user = User.find(params[:post][:current_user])
    @post = current_user.posts.create(post_params)


    respond_to do |format|
      if @post.save
         #format.html { redirect_to @post, notice: "Post was successfully created." }
        # format.json { render :json,status: :created, location: @post }
        format.json { render :json => @post }
      else
        #format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # def user_admin
    #   if current_user.admin?
    #     return true
    #  else
    #      flash[:alert] = "You don't have a permission to access this page"
    #      redirect_to root_path
    #   end
    # end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:user_id,:title, :description,:image)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="row justify-content-center"><nav class="navbar navbar-light bg-light justify-content-between">
</nav>
<div class="col-sm-4">
  <div class="card">
   <div class="card-body">
     <%= form_with(model: post) do |f| %>
     <% if post.errors.any? %>
     <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
        <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <div class="row">
      <label for="inputEmail3" class="col-sm-2 col-form-label">Title</label>
      <%= f.text_field :title, autofocus: true, autocomplete: "title",class: "form-control w-50" %>
    </div>

    <div class="row">
      <label for="inputEmail3" class="col-sm-2 col-form-label">Image</label>
      <%= f.file_field :image, autofocus: true, autocomplete: "image",class: "form-control w-50 btn btn-primary" %>
    </div>

    <div class="row">
      <label for="inputEmail3" class="col-sm-2 col-form-label">Description</label>
      <%= f.text_area :description, autofocus: true, autocomplete: "description",class: "form-control w-50" %>
    </div>
    <div class="row">
     <div class="col text-center">
      <%= f.submit "Submit",class: " btn btn-success" %>
    </div>
  </div>


  <div>
  </div>
</div>  
</div>
</div>
</div>

<% end %>
</div>

app/views/posts/_view.html.erb
<div id = "post_comment">
<%@post.comments.each do |f|%>
<%=f.comment%><br>
<%end%>
</div>

app/views/posts/edit.html.erb
<div class = "text-center">
<h1>Edit Post</h1>
</div>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', root_path %>

app/views/posts/index.html.erb
 <div class="row justify-content-center"><nav class="navbar navbar-light bg-light justify-content-between">
</nav>
<div class="col-sm-4">
  <div class="card">
   <div class="card-body">
            <table border = 1>
              <thead>
                <tr>
                  <th>Title</th>
                  <th>Description</th>
                  <th>Show</th>
                  <th>Edit</th>
                  <th>Destroy</th>
                  <th>Images</th>
                  <th>Likes</th>
                  <th colspan="3"></th>
                </tr>
              </thead>

              <tbody>
                <% @posts.each do |post| %>
                <tr>
                  <td><%= post.title %></td>
                  <td><%= post.description %></td>
                  <td><%= link_to 'Show',  post_path(post.id)%></td>
                  <td><%= link_to 'Edit', edit_post_path(post) %></td>
                  <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
                   <td><%= image_tag(post.image.url , width:100) %></td>
                 </td>
                 <td><%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%></td>
               </tr>
               <% end %>
             </tbody>
           </table>

           <br>

         </div>
       </div>
     </div>
   </div>
 <%= link_to 'New Post', new_post_path,class: "btn btn-success" %><br><br>
 <%= link_to 'Back', root_path,class: "btn btn-primary" %>

app/views/posts/new.html.erb
<div class = "text-center">
<h1>New Post</h1>
</div>

<%= render 'form', post: @post %>

<%= link_to 'Back', root_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="card" style="width: 30rem;">
  <div class="card-body">
    <div class="col-sm-12">
     <div class="mar">
      <div class="card border" style="width: 33rem;">

        <div class="row">
          <label for="inputEmail3" class="col-sm-2 col-form-label">Title</label>
          <%= @post.title %>
        </div>

        <div class="row">
          <label for="inputEmail3" class="col-sm-2 col-form-label">Description</label>
          <%= @post.description %>
        </div>

        <div class="row">
          <label for="inputEmail3" class="col-sm-2 col-form-label">Image</label>
          <%= image_tag(@post.image.url , width:200) %>
        </div>


        <%= form_for [@post, @post.comments.build]  do |f| %>
        <%= f.label 'New comment' %><br>
        <%= f.text_area :comment,id: 'input',class:"textfield" %><br>
        <%= f.submit 'Submit',class:"button btn btn-success"%>
        <% end %>

        <div id = "likkke_<%= @post.id%>">
          <strong>Likes</strong>
          <%= render 'likes/like_post',post:@post %>
        </div>


        <div id="comment_<%= @post.id %>">
          <strong>Comments</strong>
          <%= render 'comments/comment', post:@post %><br>
        </div>


        <script type="text/javascript">

         $("#new_comment").submit(function(event) {
           event. preventDefault();
    // var post_id = "<%#= @post.id %>"
    var data = $("#new_comment").serialize();
    $.ajax({
      url: "/posts/"+<%= @post.id %>+"/comments",
      type: 'POST', 
      data: data,
      success: function(a){
        alert('it works');
      }
    });
  });

</script>

</div>  
</div>
</div>
</div>
</div>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', root_path %>

app/views/posts/show.js.erb
$("#<%= @post.id %>").html("<%= escape_javascript(render partial: 'posts/view',locals: { post: @post} ) %>");
$("#show_com_<%= @post.id %>").hide();
$("#rvm_com_<%= @post.id %>").css("display", "");